### ISSUE TITLE
Dark problem in models after converting to b3dm

### ISSUE THREAD

**Issue by safa833** [AnalyticalGraphicsInc/3d-tiles#313] opened 2018-05-25 10:54 UTC
I converted to b3dm by using FME. Output:
![1](https://user-images.githubusercontent.com/10292075/40540920-7c080744-6022-11e8-9f9e-13eaadfbe4af.PNG)
I converted each obj to glTF through https://github.com/AnalyticalGraphicsInc/obj2gltf
![2](https://user-images.githubusercontent.com/10292075/40540927-7f25fd96-6022-11e8-9db6-c61879246db9.PNG)

How can i solve darkness problem ?
Thanks.

**Comment by lilleyse** [comment] 2018-05-25 15:29
obj2gltf and FME may be using different materials and/or lighting models. Check if FME provides any controls for increasing ambient light.

Closing since this is not a bug with 3d-tiles directly. Also in the future the [Cesium forum](https://groups.google.com/forum/#!forum/cesium-dev) is a better place for questions like this:

**Closed by lilleyse** 2018-05-25 15:29 UTC
